# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.1'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 6.0.3', '>= 6.0.3.3'
# Use postgresql as the database for Active Record
gem 'pg', '>= 0.18', '< 2.0'
# Use Puma as the app server
gem 'puma', '~> 4.1'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use Active Model has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Active Storage variant
# gem 'image_processing', '~> 1.2'

gem 'rack-cors'

gem 'acts_as_tenant', '~> 0.0'
gem 'devise-jwt', '~> 0.7.0'
gem 'jbuilder', '~> 2.7'
gem 'olive_branch'

group :development, :test do
  gem 'byebug'
  gem 'factory_bot_rails', '~> 6.0'
end

group :development do
  gem 'annotate', '~> 3.0'
  gem 'listen', '~> 3.2'
end
